[package]
name = "actix"
version = "0.1.0"
authors = ["EgorRepnikov <egorepnikov@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.0.0"
tokio = { version = "0.2", features = ["full"] }
serde_derive = "1.0.105"
serde = "1.0.105"
